services:
  postgres:
    image: postgres:15.3
    ports:
      - 6432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=posgtres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=posgres
