name: File Size Checker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-file-sizes:
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        run: |
          apt-get update
          apt-get install -y git bc

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create test files
        run: |
          # Create test files
          dd if=/dev/zero of=test-large.bin bs=1M count=15
          dd if=/dev/zero of=test-huge.bin bs=1M count=45

          # Show created files
          ls -lh

      - name: Check file sizes
        id: check-sizes
        run: |
          # Initialize variables for tracking findings
          large_files=""
          huge_files=""

          # For testing purposes, check all files in directory
          for file in *; do
            if [ -f "$file" ]; then
              size=$(stat -c%s "$file")
              size_mb=$(echo "scale=2; $size/1048576" | bc)
              
              echo "Checking $file: ${size_mb}MB"
              
              # Check for files over 40MB
              if (( $(echo "$size_mb > 40" | bc -l) )); then
                huge_files="${huge_files}* ${file} (${size_mb}MB)\n"
              # Check for files over 10MB
              elif (( $(echo "$size_mb > 10" | bc -l) )); then
                large_files="${large_files}* ${file} (${size_mb}MB)\n"
              fi
            fi
          done

          # Print findings for debugging
          echo "Large files found:"
          echo -e "$large_files"
          echo "Huge files found:"
          echo -e "$huge_files"

          # Set outputs for use in next steps
          echo "large_files<<EOF" >> $GITHUB_OUTPUT
          echo -e "$large_files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "huge_files<<EOF" >> $GITHUB_OUTPUT
          echo -e "$huge_files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # Fail if huge files are found
          if [ ! -z "$huge_files" ]; then
            echo "❌ Files over 40MB found!"
            exit 1
          fi

      - name: Debug Output
        if: always()
        run: |
          echo "🔍 Large files output:"
          echo "${{ steps.check-sizes.outputs.large_files }}"
          echo "🔍 Huge files output:"
          echo "${{ steps.check-sizes.outputs.huge_files }}"

      - name: Comment on PR
        if: steps.check-sizes.outputs.large_files != '' || steps.check-sizes.outputs.huge_files != ''
        uses: actions/github-script@v7
        with:
          script: |
            const largeFiles = `${{ steps.check-sizes.outputs.large_files }}`;
            const hugeFiles = `${{ steps.check-sizes.outputs.huge_files }}`;

            let comment = '## ⚠️ File Size Check Results\n\n';

            if (hugeFiles) {
              comment += '### 🚫 Files over 40MB (Not Allowed):\n' + hugeFiles + '\n';
              comment += '**These files must be removed from git history before the PR can be merged.**\n\n';
            }

            if (largeFiles) {
              comment += '### ⚠️ Large Files (Over 10MB):\n' + largeFiles + '\n';
              comment += 'Consider reducing the size of these files if possible.\n';
            }

            console.log('Would post comment:', comment);
